import fs from "node:fs";
import path from "node:path";
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const docsDir = path.join(__dirname, "docs");

// Cada projeto CLK sincronizado pelo DocsSyncCLI cai em docs/<ProjectKey>/.
// Gerar essas categorias dinamicamente evita ter que editar este arquivo
// toda vez que um novo projeto passar a sincronizar documentação.
const projectCategories = fs
  .readdirSync(docsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()
  .map((dirName) => ({
    type: "category" as const,
    label: dirName,
    items: [{ type: "autogenerated" as const, dirName }]
  }));

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Fundamentos CLOUTRIK",
      items: ["qualidade", "commits", "cicd", "observabilidade"]
    },
    {
      type: "category",
      label: "Sistemas distribuidos",
      items: ["mensageria", "microservicos", "ranking"]
    },
    ...(projectCategories.length > 0
      ? [
          {
            type: "category" as const,
            label: "Projetos",
            items: projectCategories
          }
        ]
      : [])
  ]
};

export default sidebars;
